spring.application.name=e-commerce-product-service
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/ProductBackend
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.output.ansi.enabled=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect